# Generated by Django 4.2.3 on 2023-07-05 21:20

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=400, null=True
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Men Haircut", "Men Haircut"),
                            ("Women Haircut", "Women Haircut"),
                            ("Kids Haircut", "Kids Haircut"),
                            ("Hair Coloring", "Hair Coloring"),
                            ("Hair Styling", "Hair Styling"),
                        ],
                        max_length=50,
                    ),
                ),
                ("day", models.DateField(default=datetime.datetime.now)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("3 PM", "3 PM"),
                            ("3:30 PM", "3:30 PM"),
                            ("4 PM", "4 PM"),
                            ("4:30 PM", "4:30 PM"),
                            ("5 PM", "5 PM"),
                            ("5:30 PM", "5:30 PM"),
                            ("6 PM", "6 PM"),
                            ("6:30 PM", "6:30 PM"),
                            ("7 PM", "7 PM"),
                            ("7:30 PM", "7:30 PM"),
                        ],
                        default="3 PM",
                        max_length=10,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "time_ordered",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day", "time"],
            },
        ),
    ]
