# Generated by Django 4.2.3 on 2023-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Men Haircut', 'Men Haircut'), ('Women Haircut', 'Women Haircut'), ('Kids Haircut', 'Kids Haircut'), ('Hair Coloring', 'Hair Coloring'), ('Hair Styling', 'Hair Styling')], max_length=50),
        ),
    ]
