# Generated by Django 4.2.3 on 2023-09-01 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="service",
        ),
    ]
