# Generated by Django 4.2.3 on 2023-09-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_appointment_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('replied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id', 'replied', 'name'],
            },
        ),
    ]
