# Generated by Django 4.2.3 on 2023-09-05 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0006_alter_contact_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply_text", models.TextField()),
                ("reply_date", models.DateTimeField(auto_now_add=True)),
                ("replied", models.BooleanField(default=False)),
                (
                    "contact_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.contact",
                    ),
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id", "replied", "contact_message"],
            },
        ),
    ]
