# Generated by Django 4.2.3 on 2023-09-06 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_contactreply_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreply',
            name='reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
