# Generated by Django 4.2.3 on 2023-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="name",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
